### PR TITLE
1.19 prep work

### PR DESCRIPTION
**Pull request by brainsynder-Dev**
- [x] Create the 1.19 module
- [x] Fix the NMS code for Cats and Frogs `(Thanks Mojang...)`
- [ ] Implement any 'hidden' features for the pets
- [ ] Warden Poses?
- [x] Frog open mouth? (Uses Frog Pose)
- [ ] More?

### CODE REVIEW

**Comment by brainsynder-Dev** [comment]
1.19 Final Todo List: (Maybe...)

- [x] Fix Allay riding
- [x] Double check that it still works on older versions (1.17/1.18)
- [ ] Frog Speed is WAY TO FAST
- [x] Frog Jump animation

There is probably more for this list... but this is all i can think of...

**Comment by Thatsmusic99** [comment]
Frog speed seems to follow that of other mobs so it would be worth turning this down in general.

**Comment by Thatsmusic99** [comment]
Two major issues currently stalling release:
- The fly attribute got removed from some mobs, breaking these pets (Vex, Blaze for example).
- The pet hat feature appears to be faulty.

**Comment by Thatsmusic99** [comment]
All major issues have been resolved. The hat issue was due to an issue from Spigot's early builds.

**Pull request merged**
