### PR TITLE
Add tropical fish data from v4

### PR DESCRIPTION
**Pull request by traksag**
In v5 the pet data for the tropical fish pet is missing: body colour, pattern and pattern colour. This pull request adds that data back.

### CODE REVIEW

**Review by Thatsmusic99 — COMMENTED** [review]
All seems fine here, and the code style fits in perfectly well, so good job on that!

There *was* an issue I did notice but I'm not sure if that would require my own or Brian's attention, this being that the tropical fish data file needed a reset before it appeared in the data menu since the icons were not automatically added in there. Whilst resetting the file is one alternative, it's not something I feel people should resort to if they've already customised the file.

I think that would need a bit more discussion depending on what @brainsynder-Dev's intentions were regarding this.

**Comment by Thatsmusic99** [comment]
Actually seems like code to fix that problem was already added but got commented out:

https://github.com/brainsynder-Dev/SimplePets/blob/e9c111907794a321128c90e464550dd7baa76996/MAIN/src/main/java/simplepets/brainsynder/impl/PetConfiguration.java#L127-L128

I've noticed a problem with it as well so I think I'll push any changes I make to it here as well. That way I can easily revert it if Brian disapproves of it.

**Comment by Thatsmusic99** [comment]
Pushed fixes that make this PR fully functioning (i.e. providing backwards compatibility), let me know if we're all good to go now and I'll merge this PR.

**Comment by traksag** [comment]
Are you referring to Brian or me? Auto-updating the data file for the tropical fish pet works fine on my test server.

**Comment by Thatsmusic99** [comment]
Referring to you. Already spoke with Brian, mostly telling him off for a mistake in SP's library that could've turned problematic.

**Comment by traksag** [comment]
Haha, well this PR is good to go then.

**Comment by Thatsmusic99** [comment]
Awesome stuff, I'll merge it then. Thanks once again!

**Pull request merged**
