### PR TITLE
Less glitchy horse/ravager/etc. riding

### LINKED ISSUE #60: Unusual behaviour w/ Horse, Donkey, Mule and Ravager mounting
the saddles don't go on the horses and There are mistakes when riding all types of horse and when you dismount it runs wild

I use:paper-206.jar
and: SimplePets Build #28  (21.04.2020 11:42:13) 

and sorry for my bad english

### PR DESCRIPTION
**Pull request by traksag**
Currently horse and ravager riding are pretty glitchy visually. It is also possible to use the vanilla pig and strider riding mechanics by endowing either with a saddle and holding a carrot/fungus on a stick. This is probably not desirable. Here's a video of riding a horse:

https://user-images.githubusercontent.com/58818927/124495856-ef184c00-ddb8-11eb-96f8-02dd42a7e904.mov

This pull request fixes the above issues. However, the horse jump bar cannot be used with my fix applied. Here's a video of riding a horse:

https://user-images.githubusercontent.com/58818927/124495874-f63f5a00-ddb8-11eb-9696-67299679df08.mov

As you may know, the root cause of the glitchyness is client-controlled riding of horses, ravagers, pigs and striders. The client simulates the vehicle movement itself and sends move vehicle packets to the server to update the vehicle position. The fix is to put the player on a 'seat' entity (an armour stand in this case) and put the 'seat' entity on the pet, so the player is not directly riding the pet and therefore won't simulate movement client-side.

I did some basic testing, but perhaps the seat entity breaks some other pieces of code. If anything's wrong let me know and I'll try to fix it. I guess it's possible to use the seat entity for every pet. However, they're slightly visible in spectator mode, so I opted for only using seat entities for some pets.

I also changed the repo URL to HTTPS, because compiling with Maven didn't work otherwise.

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
This is an interesting approach to the problem, I really like it!

I'll be taking a closer look at it and let @brainsynder-Dev do the same as well. The horse jump bar shouldn't be a problem, we never looked to use it regardless.

**Comment by traksag** [comment]
Woops, I overlooked committing those two things

**Review by Thatsmusic99 — COMMENTED** [review]
One issue I did find with this was that when dismounting over >1 block deep water (e.g. 2 blocks deep) and remounting over said water height, the actual pet (e.g. donkey, which I used to test this) kicks off the hidden armor stand but doesn't do the same for the player:



If you do want good news, this does not have any major consequences on entity count as the armor stand does immediately get deleted after the player dismounts it.

**Comment by Thatsmusic99** [comment]
i cannot use this review function to save my life

**Comment by traksag** [comment]
Dang nice catch! Apparently living entity passengers auto-dismount themselves if their eyes are in water and the vehicle is not "rideableUnderWater". Changed seats so they don't auto-dismount themselves in such circumstances. Also added some other stuff so seats are (hopefully) more transparent to the dismounting process.

**Comment by Thatsmusic99** [comment]
Wonderful work on this PR, the issue mentioned seems to be gone altogether. I'll pull this over now. Thank you for contributing to SimplePets!

**Pull request merged**
